### ISSUE TITLE
 Binary XML file line Error inflating class 

### ISSUE THREAD

**Issue by hasanmumin** [adform/adform-android-sdk#21]
Error message: 
```
android.view.InflateException: Binary XML file line #7: Error inflating class com.adform.sdk.pub.views.AdInline
    at android.view.LayoutInflater.createView(LayoutInflater.java:633)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
```

Fragment code:

 ```
@Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, Bundle savedInstanceState) {
        View root = inflater.inflate(R.layout.fragment_adinline, container, false);

        adInline = root.findViewById(R.id.adInline);

        // [optional] Setting base listeners for ad load status
        adInline.setListener(new AdListener() {
            @Override
            public void onAdLoadSuccess(AdInline adInline) {
            }

            @Override
            public void onAdLoadFail(AdInline adInline, String s) {
                // Setting fallback image whenever ad fails to load
                // findViewById(R.id.ad_container).setBackgroundResource(R.drawable.ic_launcher);
            }
        });

        // [optional] Setting additional listeners for ad events
        adInline.setStateListener(new AdStateListener() {
            @Override
            public void onAdVisibilityChange(AdInline adInline, boolean b) {

            }

            @Override
            public void onAdOpen(AdInline adInline) {

            }

            @Override
            public void onAdClose(AdInline adInline) {

            }
        });

        // [mandatory] Setting ad size. [optional] if set in layout XML
//        adInline.setAdSize(new AdSize(320, 50));

//        [optional] You could add to the request additional sizes.
//        adInline.setSupportedSizes(new AdSize(300, 300), new AdSize(320, 160));

//        [optional] If you want to support multiple ad sizes at the same placement without setting them, you could use additional dimensions feature.
//        adInline.setEnabledAdditionalDimensions(true);

//        [optional] If you want to setup that HTML ad would be loaded if video ads fails, you need to set fallback master tag.
//        adInline.setFallbackMasterTagId(1111111);

        // [mandatory] Setting master tag. [optional] if set in layout XML
        adInline.setMasterTagId(142493);

        // [optional] Debug mode for testing ad. Can be set in layout XML
        // adInline.setDebugMode(true);

        // [optional] You can set an animation type that could be used when ad shows in the banner.
        // adInline.setBannerAnimationType(AdformEnum.AnimationType.FADE);
        // adInline.setBannerAnimationType(AdformEnum.AnimationType.NO_ANIMATION);
        adInline.setBannerAnimationType(AdformEnum.AnimationType.SLIDE); // default

        // [optional] You can set an animation type that could be used when ad is expanded ( mraid.expand() ).
        // adInline.setModalPresentationStyle(AdformEnum.AnimationType.FADE);
        // adInline.setModalPresentationStyle(AdformEnum.AnimationType.NO_ANIMATION);
        adInline.setModalPresentationStyle(AdformEnum.AnimationType.SLIDE); // default

        // [optional] This flag sets if dim should be used in the background whenever mraid.expand() is used.
        adInline.setDimOverlayEnabled(true); // default

        adInline.setAdSize(new SmartAdSize(1920, 1080));

        // [mandatory] Send an event to start loading
        adInline.loadAd();

        return root;
    }

    @Override
    public void onResume() {
        super.onResume();
        if (adInline != null)
            adInline.onResume();
    }

    @Override
    public void onPause() {
        super.onPause();
        if (adInline != null)
            adInline.onPause();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        if (adInline != null)
            adInline.destroy();
    }
```

// fragment_adinline
```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:background="@android:color/black"
    android:layout_height="match_parent">

    <com.adform.sdk.pub.views.AdInline
        android:id="@+id/adInline"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</RelativeLayout>
```
// depencies

```
implementation ('com.google.android.gms:play-services-ads:17.1.3'){
        exclude group:'com.android.support'
    }
    implementation ('com.adform.advertising.sdk:advertising-sdk:2.13.6@aar'){
        exclude group:'com.android.support'
    }
```
it is working fine on emulator, but not on real device.

**Comment by hasanmumin** [comment]
it was a security exception. Solution:
https://stackoverflow.com/a/50795319
