### ISSUE TITLE
NPE in AdInline

### ISSUE THREAD

**Issue by rgabrysiak** [adform/adform-android-sdk#3]
Hi,

we recently released our application using AdForm SDK and we started to receive following crash reports. Below you can see full stacktrace. Please take care of this issue as soon as possible.

Package: com.eniro
Version Code: 1502845
Version Name: 8.4.4.05.1
Android: 7.0
Manufacturer: samsung
Model: SM-G925F
Date: Fri Sep 15 15:59:56 GMT+02:00 2017

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.adform.sdk.d.r.d()' on a null object reference
	at com.adform.sdk.pub.views.AdInline.onSizeChanged(AdInline.java:258)
	at android.view.View.sizeChange(View.java:18935)
	at android.view.View.setFrame(View.java:18878)
	at android.view.View.layout(View.java:18791)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.widget.ListView.setupChild(ListView.java:2260)
	at android.widget.ListView.makeAndAddView(ListView.java:2140)
	at android.widget.ListView.fillDown(ListView.java:767)
	at android.widget.ListView.fillSpecific(ListView.java:1482)
	at android.widget.ListView.layoutChildren(ListView.java:1911)
	at android.widget.AbsListView.onLayout(AbsListView.java:3008)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at com.eniro.core.android.widget.scrollingsearch.SlidingUpPanelLayout.onLayout(SlidingUpPanelLayout.java:823)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:887)
	at android.view.View.layout(View.java:18798)
	at android.view.ViewGroup.layout(ViewGroup.java:5951)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2648)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2364)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7091)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
	at android.view.Choreographer.doCallbacks(Choreographer.java:702)
	at android.view.Choreographer.doFrame(Choreographer.java:638)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6682)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by andriusmisiunas** [comment]
Hello,

We are looking into this. Thank you for reporting.

**Comment by rprunskas** [comment]
Hi, it was fixed in 2.9.1 version.
